# Makefile generated by genmake.pl
# Written by Ramo

CC=g++
BUILD=build
DIST=dist
CCFLAGS=-c -g -Wall --std=c++11
LDFLAGS=-o $(DIST)/prog -lgmp -ltasn1 

all:	$(DIST)/prog
$(DIST)/prog:	$(BUILD) $(DIST) $(BUILD)/main.o $(BUILD)/encoders.o 
	$(CC) $(BUILD)/*.o $(LDFLAGS)
$(BUILD)/main.o:	main.cpp encoders.h
	$(CC) main.cpp $(CCFLAGS) -o $(BUILD)/main.o
$(BUILD)/encoders.o:	encoders.cpp encoders.h
	$(CC) encoders.cpp $(CCFLAGS) -o $(BUILD)/encoders.o
$(BUILD):
	@mkdir $(BUILD)
$(DIST):
	@mkdir $(DIST)
clean:
	rm -rf $(BUILD) $(DIST)
install:
	install $(DIST)/prog /usr/local/bin/
love:
	@echo Not war
